name: "Setup Node.js and Dependencies"
description: "Common setup steps for Node.js projects"
inputs:
  restore-cache:
    description: "Whether to restore node_modules cache"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: setup Pnpm
      uses: pnpm/action-setup@v4.1.0
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: "pnpm"
    - name: Restore node_modules cache
      if: inputs.restore-cache == 'true'
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
