name: "Setup Node.js and Dependencies"
description: "Common setup steps for Node.js projects"
inputs:
  restore-cache:
    description: "Whether to restore node_modules cache"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: "22.x"
        cache: "npm"
    - name: Restore node_modules
      if: inputs.restore-cache == 'true'
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
