name: Node.js CI

on:
# push
#   branches: [ main ]
# pull-request:
#   branches: [ main ]
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout node
      uses: actions/checkout@v5.0.0
    - name: setup Pnpm
      uses: pnpm/action-setup@v4.1.0
    - name: Use node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm run build
