# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  #   push:
  #     branches: [ main ]
  #   pull_request:
  #     branches: [ main ]
  workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: npm install
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Setup Node.js with cache
        uses: ./.github/actions/setup-node
        with:
          restore-cache: "true"
      - name: Build
        run: npm run build

  security-scan:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Setup Node.js with cache
        uses: ./.github/actions/setup-node
        with:
          restore-cache: "true"
      - name: Aqua Security Trivy Install
        uses: aquasecurity/setup-trivy@v0.2.3
      - name: Run SAST
        run: npm run audit:trivy
      - name: Archive SAST results
        uses: actions/upload-artifact@v4
        with:
          name: sast-report
          path: report.html
