# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  #   push:
  #     branches: [ main ]
  #   pull_request:
  #     branches: [ main ]
  workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: pnpm install
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Setup Node.js with cache
        uses: ./.github/actions/setup-node
        with:
          restore-cache: "true"
      - name: Build
        run: pnpm run build

  security-scan:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Setup Node.js with cache
        uses: ./.github/actions/setup-node
        with:
          restore-cache: "true"
      - name: Aqua Security Trivy Install
        uses: aquasecurity/setup-trivy@v0.2.3
      - name: Run SAST
        run: pnpm run audit:trivy
      - name: Archive SAST results
        uses: actions/upload-artifact@v4
        with:
          name: sast-report
          path: trivy-report.html

  fake-ansible-deploy:
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
     - name: Checkout code
       uses: actions/checkout@v5.0.0
     - name: webfactory/ssh-agent
       uses: webfactory/ssh-agent@v0.9.0
       with:
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
     - name: Setup Ansible
       # autre action plus legit ?
       uses: alex-oleshkevich/setup-ansible@v1.0.1
     - name: Run ansible
       run: ansible -i ops/ansible/inventory.yaml ops/ansible/playbook.yaml
    
